### ISSUE TITLE
Responsiveness of row buttons

### ISSUE THREAD

**Issue by sakkshm26** [nrnb/nrnb.github.io#27]
The row buttons on the home page are overflowing when the width becomes less than 410px.

![Screenshot (413)](https://user-images.githubusercontent.com/87091886/145248284-24a85923-25dc-42d6-8882-ed777a5912df.png)

**Comment by Vikash-8090-Yadav** [comment]
Is this issue still active or open ? If yes, can u please assign me this issue.

@khanspers @sakkshm26 @dexterpratt @rpillich 
Thank u so much ✌️

**Comment by Shubhamrajgithub** [comment]
Can I work on this issue @AlexanderPico @khanspers.

**Comment by AlexanderPico** [comment]
> Can I work on this issue @AlexanderPico @khanspers.

@Shubhamrajgithub This is not related to NRNB GSoC projects. It's not really an issue at all, imo. Closing.
