### ISSUE TITLE
navigationbar

### ISSUE THREAD

**Issue by Maheshwarreddy970** [nrnb/nrnb.github.io#30]
navigationbar getting margin in smaller screen
![NRNB sr1](https://user-images.githubusercontent.com/118247589/225526427-50c1d04a-af19-40d0-835c-42c124a864b5.png)

**Comment by Shubhamrajgithub** [comment]
@Maheshwarreddy970  I can't find the navigation bar file or related html to get started on it. Do you have any idea.

**Comment by Shubhamrajgithub** [comment]
I have updated the margin issue and sent a PR.
