### ISSUE TITLE
Padding overlap issue on small screen.

### ISSUE THREAD

**Issue by Shubhamrajgithub** [nrnb/nrnb.github.io#32]
There has been issue with the padding on  small screen. It need to be updated in CSS.

![Screenshot (125)](https://user-images.githubusercontent.com/71963532/225720549-957cceb2-f3bf-4531-a756-f8b1a05e231d.png)

**Comment by Shubhamrajgithub** [comment]
@AlexanderPico, Can I take this issue and update remove left and right padding to avoid overlap.

**Comment by AlexanderPico** [comment]
Not important. If you're interested in NRNB GSoC, please see the project issue tracker for the scope of ideas we're interested in working on.  Minor UI/UX issues on the nrnb.org site are not worth any of our time :)
