### ISSUE TITLE
The website needs to be more responsive on mobile devices

### ISSUE THREAD

**Issue by kowais915** [nrnb/nrnb.github.io#33]
**Description**
Some of the elements of the website's landing page lack responsiveness on mobile devices. Please see the screenshots below.

**Screenshot**

Screenshot 1:

![Screenshot 1](https://user-images.githubusercontent.com/45107209/227681557-bb218931-b06d-4dcc-a32b-2475a70e714a.png)

Screenshot 2:
![Screenshot 2](https://user-images.githubusercontent.com/45107209/227681524-953b0588-8e52-47c4-b9a3-7cac595c3ae4.png)

**Comment by AlexanderPico** [comment]
Project ideas for the NRNB Google Summer of Code are over here: https://github.com/nrnb/GoogleSummerOfCode/issues

The responsiveness of the website is not a priority at this time nor is it related to GSoC projects.

Thanks for your interest in our project and welcome to open source!
