### ISSUE TITLE
Extra unwanted padding on smaller screens

### ISSUE THREAD

**Issue by Murdock9803** [nrnb/nrnb.github.io#36]
### Problem
When we see the website on smaller screens, it gains an extra black padding space at the top, which doesn't look good for a user's point of view.

Also, when the screen width goes less than 767 pixels, the page gains black space at right and left too.

### Screenshot
![Screenshot 2023-12-08 231547](https://github.com/nrnb/nrnb.github.io/assets/136724527/daaec4ad-9b6d-445c-98ef-c10193306eed)

- [x] I would like to solve this issue

**Comment by khanspers** [comment]
Hi @Murdock9803, I fixed the side padding issue. Still working on the top padding. If you have a solution, please submit a PR.

**Comment by Murdock9803** [comment]
Hello @khanspers , thank you very much for the help, I'll surely submit the PR for the top padding issue. Actually I noticed, the top padding is necessary on big screens for the navbar alignment but unnecessary on the smaller screens.

**Comment by Murdock9803** [comment]
@khanspers I created a PR for the top padding part. please review. I also want to connect with the NRNB developers community for better communication, Is there any slack channel or I should continue with mails ?

**Comment by AlexanderPico** [comment]
Hi @Murdock9803. Thanks for your interest in NRNB. This website, however, is not revelant to potential GSoC projects. Please find projects listed here: https://github.com/nrnb/GoogleSummerOfCode/issues. We are just starting to collect project ideas for 2024, so expect this to grow by February. Regardless, getting involved in the projects there will be more relevant to GSoC participation.

FYI. I'm going to close the issue tracker here to avoid confusion in the future.
