### ISSUE TITLE
Button not aligned properly on the Main page Bottom part

### ISSUE THREAD

**Issue by Murdock9803** [nrnb/nrnb.github.io#38]
### Problem Description
The Button present just above the footer at the main landing page of the website, is not aligned properly for smaller screens. This makes it look odd and requires some padding for better UI.

### Solution
There can be two good ways to make it look better, one is making it align at the middle, or give it some padding to the right side, which also goes with the alignment in the bigger screens.

### Steps to regenerate
1. go to https://nrnb.org/.
2. Opt for smaller screen (width < 767px)
3. go to the bottom of the page.

### Screenshots
Before :
![Screenshot 2023-12-10 150808](https://github.com/nrnb/nrnb.github.io/assets/136724527/d7fa327c-67b3-4f79-aee7-11928dc65d96)

After :
![Screenshot 2023-12-10 151813](https://github.com/nrnb/nrnb.github.io/assets/136724527/1d39452b-c19c-4d8d-a0d8-519a976e35b7)

### Willingness to work
- [x]  I would like to work on this issue.

**Comment by AlexanderPico** [comment]
Closing issues here. This site is not relevant to NRNB GSoC projects and is low priority at the moment.
