### ISSUE TITLE
Standard NRNB PR template missing

### ISSUE THREAD

**Issue by Murdock9803** [nrnb/nrnb.github.io#39]
There should be a Standard Pull Request template for anyone contributing to NRNB.
This would not only standardize the process, but we can track which is issue is being solved by a PR, and screenshots etc.. can also be attached.

- [x] I would like to work on this issue

**Comment by AlexanderPico** [comment]
Closing issues here. This site is not relevant to NRNB GSoC projects and is low priority at the moment.
